# File: .github/workflows/android_build.yml
# Purpose: Build a debug APK for your BlackBarCover project on GitHub Actions
# This workflow runs on every push to 'main' and can also be triggered manually.

name: Android CI

# When to trigger the workflow
on:
  push:
    branches: [ main ]        # Automatically run on push to main branch
  workflow_dispatch:           # Allows manual triggering from the Actions tab

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest     # Use latest Ubuntu runner

    steps:
      # Step 1: Check out your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java (required by Gradle)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'    # Gradle requires Java 17 for modern Android builds

      # Step 3: Make Gradle wrapper executable
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Step 4: Build the debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Step 5: Upload the resulting APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: BlackBarCover-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
