name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java JDK 17 for Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Install Android SDK and required packages
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 'latest'
          accept-android-sdk-licenses: true
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools

      # Step 4: Ensure Gradle wrapper is executable
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Step 5: Build the debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Step 6: Upload APK as artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: BlackBarCover-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
